version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db_foodgram:
    image: postgres:13
    env_file: .env 
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: scales33/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media

  frontend:
    image: scales33/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: scales33/foodgram_gateway
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/media
    ports:
      - 8000:80